### ISSUE TITLE
Finishing malware detection work (adding item to fundables list)

### ISSUE THREAD

**Issue by brainwane** [psf/fundable-packaging-improvements#10]
@xmunoz and I just talked about the work still remaining to finalize malware detection on Warehouse. Cristina, maybe you would like to submit a pull request to add a paragraph about that to https://github.com/psf/fundable-packaging-improvements/blob/master/FUNDABLES.md#security-improvements-and-prerequisites ?

**Comment by xmunoz** [comment]
yes, gladly. Could you or someone else that manages this repo add me as the assignee?

**Comment by brainwane** [comment]
Done in #11 and now at https://github.com/psf/fundable-packaging-improvements/blob/master/FUNDABLES.md#productionize-malware-detection . Thanks @xmunoz!
