### ISSUE TITLE
Implement PEP 600

### ISSUE THREAD

**Issue by xmunoz** [psf/fundable-packaging-improvements#17]
Finish the "perennial" [manylinux PEP](https://www.python.org/dev/peps/pep-0600/) and get it approved and implemented to reduce the churn of hardcoded, brittle manylinux standards and react better to ongoing platform change.

**Comment by di** [comment]
The PEP has been approved and there is an in-progress rollout issue here: https://github.com/pypa/manylinux/issues/542

**Comment by xmunoz** [comment]
Thanks for that. From the linked issue, it looks like most of the implementation work is done, so maybe this isn't a great candidate for funding.

**Comment by xmunoz** [comment]
#39 done
