### ISSUE TITLE
Implement PEP 656 -- Platform Tag for Linux Distributions Using Musl to improve package usage on containers

### ISSUE THREAD

**Issue by xmunoz** [psf/fundable-packaging-improvements#26]
Ref: https://www.python.org/dev/peps/pep-0656/

> With the wide use of containers, distributions such as Alpine Linux [alpine], have been gaining more popularity than ever. Many of them based on musl [musl], a different libc implementation from glibc, and therefore cannot use the existing manylinux platform tags. This means that Python package projects cannot deploy binary distributions on PyPI for them. Users of such projects demand build constraints from those projects, putting unnecessary burden on project maintainers.

**Comment by pradyunsg** [comment]
This has been implemented.
