### ISSUE TITLE
suggestion for addition: conda-press

### ISSUE THREAD

**Issue by brainwane** [psf/fundable-packaging-improvements#4]
@pradyunsg [mentioned](http://kafka.dcpython.org/day/pypa-dev/2020-05-12/):

> Aaand, another item for "Fundable Python Packaging" projects would be conda-press (pressing conda packages into wheels). That could be the "automated wheel building" solution for PyPI. There's interest in funding mentioned by the author: https://github.com/regro/conda-press/issues/63#issuecomment-592124378 (and this was discussed in PyCon 2019's packaging summit as well). 

@scopatz would you like to [take a look at this repo](https://github.com/psf/fundable-packaging-improvements) and potentially add a suggestion regarding conda-press to https://github.com/psf/fundable-packaging-improvements/blob/master/FUNDABLES.md#better-specifications-toolchain-and-services-for-building-distributions ?

**Comment by scopatz** [comment]
Yep! Will do tomorrow!

**Comment by brainwane** [comment]
@scopatz Hope you can follow up! Thanks.

**Comment by pradyunsg** [comment]
A very gentle nudge on this @scopatz!

**Comment by scopatz** [comment]
Yep, I put in a PR over the weekend

**Comment by brainwane** [comment]
@scopatz Do you mean https://github.com/scopatz/fundable-packaging-improvements/pull/1 ? If so, it seems you opened it against your own fork, not this main repo....

**Comment by ericholscher** [comment]
Just wanted to bump this with a 👍 . Could also be a good option for a CZI grant, but not sure which org would apply for it.
