### ISSUE TITLE
dealing with include_package_data in setuptools

### ISSUE THREAD

**Issue by brainwane** [psf/fundable-packaging-improvements#42]
"Ignoring package_data when `include_package_data` is True" https://github.com/pypa/setuptools/issues/1461

@timabbott recently brought this to my attention and noted that this is a Python packaging system issue that is linked from ~10 other projects that had to work around it, and that it seems fairly high-impact and solvable (once decisions are hashed out).

**Comment by brainwane** [comment]
Heads-up @s-mm.

**Comment by pradyunsg** [comment]
The relevant issue seems to have been closed. :)
