### ISSUE TITLE
Close the "Add support for pyproject.toml as a way to configure setuptools" item?

### ISSUE THREAD

**Issue by sinoroc** [psf/fundable-packaging-improvements#53]
Should the "*Add support for pyproject.toml as a way to configure setuptools*" ([current link](https://github.com/psf/fundable-packaging-improvements/blob/master/FUNDABLES.md#add-support-for-pyprojecttoml-as-a-way-to-configure-setuptools) item be closed? It seems to me like it [has been implemented](https://github.com/pypa/setuptools/issues/1688).

If yes, should it be removed or moved to a different section? Which one? There is a section "*Items that have now been funded*", but as far as I can tell it was done without dedicated funding.

**Comment by di** [comment]
Yes, this appears to be mostly done and likely does not require funding anymore.

**Comment by sinoroc** [comment]
@di How to proceed? Any preference?

* Remove the item (we always have the *git log*)
* Move to a different section? What title?
* Move to a different document? What title?

**Comment by di** [comment]
I think I'd be fine with just removing it!

**Comment by sinoroc** [comment]
@abravalheri Do you agree this item can be removed?

**Comment by abravalheri** [comment]
Yes, it was implemented (at least the basic functionality described in PEP 621).
