### ISSUE TITLE
Document how to contact the Packaging WG

### ISSUE THREAD

**Issue by rpdelaney** [psf/fundable-packaging-improvements#8]
> Please contact the Packaging WG to ask us to estimate how much one of these improvements would cost; we'll get back to you within a few business days.

Okay. How? A hyperlink of some kind, probably on `contact`, would help. Clicking the link to [Packaging Working Group](https://wiki.python.org/psf/PackagingWG) takes me to a wiki page. About 1/3 of the way down there are email addresses for the working group chair and co-chair. 

> To contact the Packaging WG, email Ewa Jodlowska. 

I humbly submit that this is too much effort for someone who wants to give you money to figure out how.

**Comment by di** [comment]
Thanks!
